development:
  adapter: postgresql
  database: cmpc_v2_database_development
  host: localhost

test:
    adapter: postgresql
    database: cmpc_v2_database_test
    host: localhost

production:
    adapter: postgresql
    database: cmpc_v2_production
    host: localhost